name: 'Libvmi setup'
description: 'This actions installs LibVMI on the system'
author: 'Mathieu Tarral'
runs:
    using: 'composite'
    steps:
      - name: Ensure sudo is available (manylinux container compat)
        shell: bash
        run: |
          if [ "$EUID" -eq 0 ]; then
            apt-get update && apt-get install -y sudo
          fi

      - name: install dependencies
        shell: bash
        run: sudo apt-get update && sudo apt-get install -qq cmake bison flex check libjson-c-dev libglib2.0-dev libxenstore3.0 libxen-dev libvirt-dev

      - name: clone libvmi
        uses: actions/checkout@v2
        with:
          repository: libvmi/libvmi
          path: libvmi
          # pinned to a specific commit to avoid breakage
          ref: '45b32c0f0003b4037700a1b534879b7d8bee5de0'

      - name: install libvmi
        shell: bash
        run: |
          cmake -B build -DCMAKE_INSTALL_PREFIX=/usr .
          cmake --build build
          sudo cmake --build build --target install
        working-directory: libvmi
