# Main CI
name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7 🐍
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: install flake8
        run: pip install flake8

      - name: lint
        run: flake8 --show-source --statistics --max-line-length=127

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
        with:
          path: python-libvmi

      - name: Install Libvmi
        uses: ./python-libvmi/.github/actions/libvmi-setup

      - name: Set up Python 🐍
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: install python-libvmi 🔨
        run: |
          pip install .
        working-directory: python-libvmi

      - name: smoke test
        run: python -c 'from libvmi import Libvmi'

      - name: build sdist and bdist_wheel
        run: |
          python -m pip install wheel
          python setup.py sdist
          python setup.py bdist_wheel
        working-directory: python-libvmi

  publish:
    needs: build
    runs-on: ubuntu-latest

    # if push on master and tag is 'v*'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1

      - name: Install Libvmi
        uses: ./.github/actions/libvmi-setup

      - name: Set up Python 3.7 🐍
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Build 🔨
        run: |
          python -m pip install wheel
          python setup.py sdist
          python setup.py bdist_wheel

      - name: Publish on PyPI 🚀
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.ACCESS_TOKEN }}
